### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by nakayuki805** [nakayuki805/AbemaTVChromeExtension#12]
コメント区切り線の位置がずれることがある
コメント無効時が誤判定される？(未確認)
コメント欄のスクロールバー周り不安定 古いコメント欄非表示のときとか
音量やフルスクリーンボタンがコメント欄に隠れる(コメ欄非表示にしてもすぐ復活は修正済)

**Comment by pokecal** [comment]
4番目は私にとって狙い通りの仕様ですが、ドラッグで位置変更できるようにすることは可能です。
またはオプション開閉ボタンと合わせて、これら専用のスペースを確保または自動開閉するようにした方がいいかもしれません。

**Comment by nakayuki805** [comment]
4番目はバグというよりは改善案として挙げましたが、コメ欄閉じればいいのですが必要ありそうであれば単純に横にずらすのでもいいかもしれません。

上に挙げたもの大半は改善しているようです。現在確認しているのは
- コメント数が無効になってから映像が切り替わるまで数秒ラグがある

**Comment by pokecal** [comment]
ラグへの対応は時間決め打ち(7カウント固定)ですが、実際には5～10程度のバラツキを確認済。
例えばこれを短めの5カウントにしておき、何かの入力で2カウント延長、のような手動対応も考えましたが、入力方法を決めかねて未実装です。

**Comment by nakayuki805** [comment]
ラグ問題含め大体解決済みなのでこれ閉じておきます
