### ISSUE TITLE
流れるコメントフォントサイズ%指定

### ISSUE THREAD

**Issue by nakayuki805** [nakayuki805/AbemaTVChromeExtension#72]
画面サイズをコロコロ変えて視聴するので流れるコメントのフォントサイズはピクセルではなく%で指定したい
(報告フォームで送られた未実装の内容をとりあえずissueに挙げておきます)

**Comment by pokecal** [comment]
font-sizeにvh使っておけばいいのかな？サイズ変更ごとにcss作り直してもいいけど。

**Comment by nakayuki805** [comment]
vhでよさそうですね。pxかvhかを選択する設定項目を追加するとか
